/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Identity and capabilities. Clients use `id` to recognize a paired server at a new address. */
        get: operations["getServer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["renameServer"];
        trace?: never;
    };
    "/clock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Server time for a first clock-offset estimate. The socket's clock messages refine it. */
        get: operations["getClock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description WebSocket for live updates and Whole-Home Sync. Every frame is `{"type", "data"}`.
         *
         *     Server to client: `hello` {serverTime}, `clock` {t0, t1}, `activity` (Event),
         *     `live.changed` (refetch tuners and sessions), `sync.state` (RoomState), `error` {code, message}.
         *
         *     Client to server: `clock` {t0}, `sync.join` {room, channelId}, `sync.leave` {room},
         *     `sync.command` {room, action: play|pause|seek|live|latency, mediaTime, latency}.
         *
         *     Rooms are `channel:<id>` (everyone on a channel, following live) or `group:<code>`
         *     (shared controls). At server time T a room shows media time
         *     `anchorMedia + (T - anchorServer) * rate`, where media time is the segment
         *     program date-time (Unix ms). See docs/decisions/0003-whole-home-sync.md.
         */
        get: operations["openSocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Tuners and signal, encoder and ffmpeg, storage, guide freshness, what the relay is carrying, connected apps, and recent activity. */
        get: operations["getDiagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Find HDHomeRun tuners by broadcast, or read one address. Reads the lineup only. */
        post: operations["discoverSources"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSources"];
        put?: never;
        post: operations["addSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchChannel"];
        trace?: never;
    };
    "/airings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAirings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guide/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshGuide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Start or join live playback. Everyone on the same frequency shares one tuner.
         *     Send `caps` (what this device can play) and optional `prefs`; the server picks a
         *     rendition and explains the choice in `stream.reason`. `rendition` forces a specific
         *     one. `profile`/`audio`/`pictureMode` are the older web fields and still work.
         */
        post: operations["watchChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watch/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopWatching"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Live tuner status, including tuners held by other devices. */
        get: operations["listTuners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecordings"];
        put?: never;
        /** @description Record a channel now. When the guide has the current airing, the recording runs to its end plus padding. */
        post: operations["startRecording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteRecording"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopRecording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{id}/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["playRecording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["saveProgress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{id}/watched": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setWatched"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadRecording"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{id}/markers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMarkers"];
        put?: never;
        post: operations["addMarker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{id}/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Find commercial breaks (comskip when installed, otherwise black frames). */
        post: operations["detectBreaks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteMarker"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Upcoming recordings from passes for the next 14 days, with conflicts marked. */
        get: operations["getSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["skipAiring"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/passes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPasses"];
        put?: never;
        post: operations["addPass"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/passes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deletePass"];
        options?: never;
        head?: never;
        patch: operations["updatePass"];
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/virtuals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listVirtuals"];
        put?: never;
        post: operations["createVirtual"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/virtuals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateVirtual"];
        trace?: never;
    };
    "/virtuals/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["virtualSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/virtuals/{id}/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["playVirtual"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put: operations["putSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStorage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadBackup"];
        put?: never;
        post: operations["restoreBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Stable machine code, for example tuners_busy, disk_low, not_found, bad_request. */
            code: string;
            /** @description Short text safe to show a user. */
            message: string;
            tuners?: components["schemas"]["Tuner"][];
            /** Format: int64 */
            freeBytes?: number;
            /** Format: int64 */
            needBytes?: number;
        } & {
            [key: string]: unknown;
        };
        RoomState: {
            room: string;
            /** Format: int64 */
            channelId?: number;
            /** @enum {string} */
            mode: "follow" | "group";
            /** @description Server Unix ms when the anchor was set */
            anchorServer: number;
            /** @description Program date-time (Unix ms) playing at anchorServer */
            anchorMedia: number;
            /** @enum {number} */
            rate: 0 | 1;
            /** @enum {string} */
            latency: "lowest" | "balanced" | "stable";
            version: number;
            members: number;
        };
        ServerInfo: {
            id: string;
            name: string;
            version: string;
            apiVersion: number;
            encoder?: string;
            tunerCount?: number;
            features: string[];
        };
        Device: {
            deviceId: string;
            friendlyName: string;
            modelNumber?: string;
            firmwareName?: string;
            firmwareVersion?: string;
            upgradeAvailable?: string;
            baseUrl: string;
            lineupUrl?: string;
            tunerCount: number;
            priority?: number;
            lastSeen?: string;
        };
        Source: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            kind: "m3u" | "link" | "folder";
            name: string;
            url?: string;
            xmltvUrl?: string;
            enabled: boolean;
        };
        Channel: {
            /** Format: int64 */
            id: number;
            deviceId: string;
            guideNumber: string;
            guideName: string;
            displayNumber: string;
            displayName: string;
            videoCodec?: string;
            audioCodec?: string;
            hd: boolean;
            favorite: boolean;
            enabled: boolean;
            hidden: boolean;
            present: boolean;
        };
        ChannelPatch: {
            favorite?: boolean;
            enabled?: boolean;
            hidden?: boolean;
            customName?: string;
            customNumber?: string;
        };
        Airing: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            channelId: number;
            title: string;
            subtitle?: string;
            description?: string;
            category?: string;
            programId?: string;
            new?: boolean;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
        };
        /**
         * @description broadcast rebuilds interlaced video at 60 frames a second; smooth uses motion-compensated deinterlacing; film recovers 24p.
         * @enum {string}
         */
        PictureMode: "broadcast" | "smooth" | "film";
        Tuner: {
            index: number;
            guide?: string;
            name?: string;
            target?: string;
            ours: boolean;
            strength?: number;
            quality?: number;
            symbol?: number;
            viewers?: number;
        };
        /** @description What the client can decode and display. */
        Caps: {
            /** @enum {string} */
            platform?: "tvos" | "ios" | "ipados" | "macos" | "visionos" | "web";
            video?: ("h264" | "hevc" | "mpeg2")[];
            audio?: ("aac" | "ac3" | "eac3")[];
            maxHeight?: number;
            /** @enum {string} */
            network?: "lan" | "wifi" | "cellular" | "remote";
        };
        /** @description The viewer's choices. Empty means automatic. */
        Prefs: {
            /** @enum {string} */
            quality?: "auto" | "original" | "high" | "medium" | "saver";
            /** @enum {string} */
            audio?: "auto" | "surround" | "stereo";
            picture?: components["schemas"]["PictureMode"];
        };
        StreamInfo: {
            rendition: string;
            /** @enum {string} */
            video: "copy" | "1080" | "720" | "540";
            /** @enum {string} */
            audio: "copy" | "aac2" | "aac6";
            mode?: components["schemas"]["PictureMode"];
            /** @description Short, user-facing explanation of the choice */
            reason: string;
            sourceVideo?: string;
            sourceAudio?: string;
            encoder?: string;
        };
        WatchSession: {
            /** Format: int64 */
            channelId: number;
            /**
             * @description HLS playlist path, relative to the server origin. Every segment carries
             *     EXT-X-PROGRAM-DATE-TIME on the channel's shared timeline, identical across renditions.
             */
            playlist: string;
            rendition: string;
            stream: components["schemas"]["StreamInfo"];
            profile?: string;
            audio?: string;
            encoder: string;
            picture?: components["schemas"]["PictureMode"];
            videoMode?: string;
            shared: boolean;
            viewers: number;
            frequencyHz?: number;
            program?: number;
            hints?: string[];
            tuners?: components["schemas"]["Tuner"][];
        };
        Recording: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            channelId: number;
            guideNumber: string;
            title: string;
            subtitle?: string;
            description?: string;
            category?: string;
            programId?: string;
            /** @enum {string} */
            status: "recording" | "complete" | "failed" | "stopped" | "imported";
            error?: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endsAt?: string;
            /** Format: date-time */
            endedAt?: string;
            /** Format: int64 */
            bytes?: number;
            position?: number;
            durationSec?: number;
            watched?: number;
        };
        Marker: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            recordingId?: number;
            start: number;
            end: number;
        };
        Pass: {
            /** Format: int64 */
            id?: number;
            title?: string;
            /** Format: int64 */
            channelId?: number;
            kind?: string;
            padBefore?: number;
            padAfter?: number;
            priority?: number;
            /** @enum {string} */
            episodes?: "all" | "new";
            /** @enum {string} */
            keepMode?: "all" | "latest";
            keepCount?: number;
            limitCount?: number;
            rerecord?: boolean;
            commercials?: boolean;
            /** @description HH:MM local */
            timeStart?: string;
            /** @description HH:MM local */
            timeEnd?: string;
            /** @enum {string} */
            matchKind?: "title" | "contains" | "category";
        };
        PassList: {
            passes: components["schemas"]["Pass"][];
        };
        PlannedAiring: {
            /** Format: int64 */
            passId: number;
            airing: components["schemas"]["Airing"];
            priority: number;
            padBefore: number;
            padAfter: number;
            conflict: boolean;
            skipped: boolean;
            reason?: string;
        };
        Event: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            at: string;
            kind: string;
            message: string;
        };
        VirtualChannel: {
            /** Format: int64 */
            id: number;
            number: string;
            name: string;
            orderMode?: string;
            ruleTitle?: string;
            recordings: number[];
        };
        Slot: {
            /** Format: int64 */
            recordingId: number;
            title: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
        };
        Settings: {
            /** @enum {string} */
            layout?: "auto" | "desktop" | "tv" | "phone";
            recordingsPath?: string;
            /** @enum {string} */
            profile?: "transparent" | "balanced" | "saver";
            /** @enum {string} */
            audio?: "stereo" | "surround";
            encoder?: string;
            /** @description Free-space reserve in GB; 0 turns it off */
            watermarkGB?: string;
            pictureMode?: components["schemas"]["PictureMode"];
            /** @enum {string} */
            autoplay?: "0" | "1";
            /** @enum {string} */
            hdhrEmulate?: "0" | "1";
            /** @enum {string} */
            setupComplete?: "0" | "1";
            /** @description 1 when this catalog should show the setup wizard. Set by the server; ignored on write. */
            needsSetup?: "0" | "1";
        };
    };
    responses: {
        /** @description Done */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    ok?: boolean;
                };
            };
        };
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        service: string;
                    };
                };
            };
        };
    };
    getServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerInfo"];
                };
            };
        };
    };
    renameServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Updated server info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerInfo"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getClock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server time */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Unix milliseconds */
                        serverTime: number;
                    };
                };
            };
        };
    };
    openSocket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching to WebSocket */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDiagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Diagnostics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The household profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        id?: number;
                        name?: string;
                        auth?: string;
                    };
                };
            };
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tuner and source devices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        devices: components["schemas"]["Device"][];
                    };
                };
            };
        };
    };
    discoverSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Host or host:port. Empty broadcasts. */
                    ip?: string;
                };
            };
        };
        responses: {
            /** @description Devices after the refresh */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        devices: components["schemas"]["Device"][];
                        found: number;
                    };
                };
            };
            500: components["responses"]["Error"];
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description M3U, stream link, and folder sources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sources: components["schemas"]["Source"][];
                    };
                };
            };
        };
    };
    addSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    kind: "m3u" | "link" | "folder";
                    name?: string;
                    /** @description Playlist URL, stream URL, or folder path */
                    url?: string;
                    xmltvUrl?: string;
                };
            };
        };
        responses: {
            /** @description Source added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        source?: components["schemas"]["Source"];
                        added?: number;
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    listChannels: {
        parameters: {
            query?: {
                /** @description When 1, only channels that belong on the guide (present, enabled, not hidden). */
                guide?: "1";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lineup */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        channels: components["schemas"]["Channel"][];
                    };
                };
            };
        };
    };
    patchChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelPatch"];
            };
        };
        responses: {
            /** @description Updated channel */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listAirings: {
        parameters: {
            query?: {
                /** @description How far ahead to return listings. */
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Guide listings from 30 minutes ago through the window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        airings: components["schemas"]["Airing"][];
                    };
                };
            };
        };
    };
    refreshGuide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listings reloaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        airings?: number;
                    };
                };
            };
            500: components["responses"]["Error"];
        };
    };
    watchChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    channelId: number;
                    caps?: components["schemas"]["Caps"];
                    prefs?: components["schemas"]["Prefs"];
                    /** @description Force a rendition key, for example copy.copy or 720.aac2.broadcast */
                    rendition?: string;
                    /**
                     * @deprecated
                     * @enum {string}
                     */
                    profile?: "transparent" | "balanced" | "saver";
                    /**
                     * @deprecated
                     * @enum {string}
                     */
                    audio?: "stereo" | "surround";
                    pictureMode?: components["schemas"]["PictureMode"];
                };
            };
        };
        responses: {
            /** @description Live session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchSession"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    stopWatching: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The rendition this viewer joined; empty releases from the busiest */
                    rendition?: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    listTuners: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tuners */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tuners: components["schemas"]["Tuner"][];
                        encoder?: string;
                    };
                };
            };
        };
    };
    listRecordings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recordings, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        recordings: components["schemas"]["Recording"][];
                    };
                };
            };
        };
    };
    startRecording: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    channelId: number;
                    minutes?: number;
                    title?: string;
                };
            };
        };
        responses: {
            /** @description Recording started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recording"];
                };
            };
            409: components["responses"]["Error"];
            507: components["responses"]["Error"];
        };
    };
    deleteRecording: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            404: components["responses"]["Error"];
        };
    };
    stopRecording: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    playRecording: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    pictureMode?: components["schemas"]["PictureMode"];
                };
            };
        };
        responses: {
            /** @description Playback for a finished or in-progress recording */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        playlist: string;
                        /** @description Resume position in seconds */
                        position: number;
                        /** @description True while the recording is still being written */
                        growing: boolean;
                        markers: components["schemas"]["Marker"][];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    saveProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    position: number;
                };
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        position?: number;
                    };
                };
            };
        };
    };
    setWatched: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    watched: boolean;
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    downloadRecording: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The original broadcast */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "video/mp2t": string;
                };
            };
        };
    };
    listMarkers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commercial markers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        markers: components["schemas"]["Marker"][];
                    };
                };
            };
        };
    };
    addMarker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    start: number;
                    end: number;
                };
            };
        };
        responses: {
            /** @description Marker added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Marker"];
                };
            };
        };
    };
    detectBreaks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Markers after detection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        markers: components["schemas"]["Marker"][];
                    };
                };
            };
        };
    };
    deleteMarker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    getSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Planned recordings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tunerCount: number;
                        items: components["schemas"]["PlannedAiring"][];
                    };
                };
            };
        };
    };
    skipAiring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    programId?: string;
                    title?: string;
                    subtitle?: string;
                    /** Format: int64 */
                    channelId?: number;
                    /** Format: date-time */
                    start?: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Ok"];
        };
    };
    listPasses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Passes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassList"];
                };
            };
        };
    };
    addPass: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    /**
                     * Format: int64
                     * @description 0 records on any channel
                     */
                    channelId?: number;
                };
            };
        };
        responses: {
            /** @description Passes after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassList"];
                };
            };
        };
    };
    deletePass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Passes after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassList"];
                };
            };
        };
    };
    updatePass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Pass"];
            };
        };
        responses: {
            /** @description Passes after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassList"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent activity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events: components["schemas"]["Event"][];
                    };
                };
            };
        };
    };
    listVirtuals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library channels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        virtuals: components["schemas"]["VirtualChannel"][];
                    };
                };
            };
        };
    };
    createVirtual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    number?: string;
                    name: string;
                    recordings?: number[];
                };
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualChannel"];
                };
            };
        };
    };
    updateVirtual: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    orderMode?: "custom" | "release" | "random" | "season" | "show" | "marathon";
                    ruleTitle?: string;
                    recordings?: number[];
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualChannel"];
                };
            };
        };
    };
    virtualSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Library channel slots for the next 48 hours */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        virtuals: (components["schemas"]["VirtualChannel"] & {
                            slots?: components["schemas"]["Slot"][];
                        })[];
                    };
                };
            };
        };
    };
    playVirtual: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    index?: number;
                    pictureMode?: components["schemas"]["PictureMode"];
                };
            };
        };
        responses: {
            /** @description Playback for one recording on the channel. Uses no tuner. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        usesTuner?: boolean;
                        index?: number;
                        count?: number;
                        playlist?: string;
                        number?: string;
                        name?: string;
                        recording?: components["schemas"]["Recording"];
                        markers?: components["schemas"]["Marker"][];
                    };
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings with defaults filled in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    putSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description Saved settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getStorage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recordings disk */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        freeBytes?: number;
                        /** Format: int64 */
                        totalBytes?: number;
                        watermarkGB?: number;
                    };
                };
            };
        };
    };
    downloadBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog database (channels edits, passes, markers, settings). Video files are not included. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    restoreBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            200: components["responses"]["Ok"];
        };
    };
}
