ALTER TABLE channels ADD COLUMN art_width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE channels ADD COLUMN art_height INTEGER NOT NULL DEFAULT 0;
ALTER TABLE airings ADD COLUMN image_width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE airings ADD COLUMN image_height INTEGER NOT NULL DEFAULT 0;
