ALTER TABLE recordings ADD COLUMN season INTEGER NOT NULL DEFAULT 0;
ALTER TABLE recordings ADD COLUMN episode INTEGER NOT NULL DEFAULT 0;
ALTER TABLE recordings ADD COLUMN episode_label TEXT NOT NULL DEFAULT '';
ALTER TABLE recordings ADD COLUMN original_air TEXT NOT NULL DEFAULT '';
