package guide

import "strings"

// calls maps a primary call sign to its network.
// Translators and diginets are left out. Guide names cover a station the table misses.
var calls = map[string]string{}

func init() {
	put("ABC", `
		WABC KABC WLS WPVI WFAA KGO WSB KTRK WJLA WCVB KNXV KOMO WFTS KSTP WPLG
		KMGH WFTV WEWS KXTV KDNL KATU WSOC WTAE WTVD WMAR WKRN KTVX KSAT KMBC
		WSYX WRTV WXYZ KVUE KGTV WTNH WISN WCPO WLOS KOCO KTNV WVEC KOAT
		KETV WOI WHAS KMIZ
	`)
	put("CBS", `
		WCBS KCBS WBBM KYW KTVT KPIX WANF KHOU WUSA WBZ KPHO KIRO WTSP WCCO WFOR
		KCNC WKMG WOIO KOVR KMOV KOIN WBTV KDKA WNCN WJZ WTVF KUTV KENS KCTV
		WBNS WTTV WWJ KEYE KFMB WFSB WDJT WKRC WSPA KWTV KLAS WTKR KRQE
		KMTV KCCI WLKY
	`)
	put("FOX", `
		WNYW KTTV WFLD WTXF KDFW KTVU WAGA KRIV WTTG WFXT KSAZ KCPQ WTVT KMSP WSVN
		KDVR WOFL WJW KTXL KTVI KPTV WJZY WPGH WRAZ WBFF WZTV KSTU KABB WDAF
		WXIN WJBK KTBC KSWB WTIC WITI WXIX WHNS KOKH KVVU WVBT
		KPTM KDSM
	`)
	put("NBC", `
		WNBC KNBC WMAQ WCAU KXAS KNTV WXIA KPRC WRC WBTS KPNX KING WFLA KARE WTVJ
		KUSA WESH WKYC KCRA KSDK KGW WCNC WPXI WRAL WBAL WSMV KSL WOAI KSHB
		WCMH WTHR WDIV KXAN KNSD WVIT WTMJ WLWT WYFF KFOR KSNV WAVY KOB
		WOWT WHO
	`)
}

func put(network, list string) {
	for _, call := range strings.Fields(list) {
		calls[call] = network
	}
}
