export const copy = {
  sources: {
    title: "Sources",
    lead: "The server reads the lineup only. It does not open a tuner from this screen.",
    search: "Search the network",
    look: "Look harder",
    lookHint: "Checks this network for tuners and servers.",
    lookEmpty: "Nothing else answered.",
    free: "Add free channels",
    freeHint: "Looks for a free-channel server already on this network.",
    freeEmpty: "No free-channel server answered.",
    add: "Add",
    lookup: "Add by address",
    address: "Address",
    addressHint: "A tuner, or a server that speaks HDHomeRun. Add the port if it is not 80.",
    none: "No HDHomeRun has answered yet.",
    tuners: "tuners",
    firmware: "Firmware",
    scan: "Scan channels",
    scanning: "Scanning for channels.",
    channels: "Lineup",
    enabled: "On guide",
    hidden: "Hidden",
    name: "Name on the guide",
    number: "Number",
    match: "Guide match",
    matchHint: "Leave guide match blank to use the number and call sign.",
    groups: "Groups",
    groupsHint: "News, Sports, -Shopping. Leave blank to keep every group.",
    file: "Playlist file",
    pick: "Choose what to keep",
  },
  library: {
    title: "Library",
    body: "Recordings gather here by show. The guide is the place to start.",
  },
  schedule: {
    title: "Schedule",
  },
  settings: {
    title: "Settings",
    layout: "Layout",
    layoutHint: "Auto follows the window. TV uses the large guide you can drive with arrows.",
    recordings: "Recordings folder",
    recordingsHint: "The container writes the original broadcast files on the recordings share.",
    reserve: "Keep this much free",
    reserveHint: "Use 0 to turn the reserve off. A show already recording is left alone.",
    backup: "Download backup",
    backupHint: "The backup is the catalog: channels, passes, and markers. The video files stay on the recordings share.",
    support: "Download a support bundle",
    supportHint: "Logs, versions, and settings. Passwords are left out.",
    guideAccount: "Schedules Direct",
    guideAccountHint: "Fills channels the tuner guide skips. Fourteen days when the account allows it.",
    guideLineup: "Lineup",
    guideAddress: "Guide address",
    guideAddressHint: "An XMLTV link for channels the tuner guide skips.",
    movieArt: "Movie artwork",
    movieArtHint: "Fills posters the guide does not include.",
    hideScores: "Hide scores",
    hideScoresHint: "A recorded game stays hidden until you watch it.",
    scoresFrom: "Scores from ESPN's public scoreboard",
    scoresFromSportsDB: "Scores from TheSportsDB",
    liveScores: "Live scores",
    liveScoresHint: "On asks your server for the scoreboard. Off sends nothing.",
    sportsdbKey: "TheSportsDB key",
    sportsdbKeyHint: "Optional. Your own key. None is included.",
    updates: "Check for updates",
    updatesHint: "Once a day. Nothing else is sent.",
    passwordTitle: "This server is for the home network",
    passwordBody: "A password is required before remote access.",
    profile: "Profile",
  },
} as const;
