export const copy = {
  sources: {
    title: "Sources",
    lead: "The server reads the lineup only. It does not open a tuner from this screen.",
    search: "Search the network",
    look: "Look harder",
    lookHint: "Checks this network for tuners and servers.",
    lookEmpty: "Nothing else answered.",
    free: "Add free channels",
    freeHint: "Looks for a free-channel server already on this network.",
    freeEmpty: "No free-channel server answered.",
    add: "Add",
    lookup: "Add by address",
    address: "Address",
    addressPlaceholder: "IP address or name",
    addressHint: "A tuner, or a server that speaks HDHomeRun. Add the port if it is not 80.",
    none: "No HDHomeRun has answered yet.",
    tuners: "tuners",
    firmware: "Firmware",
    scan: "Scan channels",
    scanning: "Scanning for channels.",
    remove: "Remove",
    offline: (when: string) => (when ? `Offline. Last seen ${when}.` : "Offline."),
    streams: (used: number, limit: number) => `${used} of ${limit} streams`,
    removeLabel: (name: string) => `Remove ${name}`,
    removeConfirm: (name: string) =>
      `Remove ${name}? Its channels leave the lineup. Favorites and passes move to another tuner with the same channel, and the other passes go. Recordings stay.`,
    channels: "Lineup",
    enabled: "On guide",
    hidden: "Hidden",
    name: "Name on the guide",
    number: "Number",
    match: "Guide match",
    matchHint: "Leave guide match blank to use the number and call sign.",
    atsc3: "ATSC 3.0",
    encrypted: (atsc3: boolean) =>
      atsc3 ? "Encrypted (ATSC 3.0 DRM). Only the tuner maker's app can play it." : "Copy protected. Only the tuner maker's app can play it.",
    playsAs: (n: string) => `Encrypted (ATSC 3.0 DRM). Plays and records ${n}, the same station in ATSC 1.0.`,
    twinShow: "Show",
    twinChoices: {
      atsc3: "3.0 only",
      atsc1: (n: string) => (n ? `1.0 only (${n})` : "1.0 only"),
      both: "Both",
    },
    twinOf: (n: string) => `Same station as ${n} in ATSC 3.0`,
    groups: "Groups",
    groupsHint: "News, Sports, -Shopping. Leave blank to keep every group.",
    file: "Playlist file",
    pick: "Choose what to keep",
  },
  library: {
    title: "Library",
    body: "Recordings gather here by show. The guide is the place to start.",
  },
  schedule: {
    title: "Schedule",
  },
  settings: {
    title: "Settings",
    liveDelay: "Live delay",
    liveDelayHint: "How far behind live a channel plays when this device starts it. Lowest is about 6 seconds, Balanced 16, Stable 20. Apple devices play at Balanced or Stable.",
    layout: "Layout",
    layoutHint: "Auto follows the window. TV uses the large guide you can drive with arrows.",
    recordings: "Recordings folder",
    recordingsHint: "The original broadcast files. To keep them somewhere else, mount that folder at /config/work/recordings.",
    byShow: "Space by show",
    byShowEmpty: "No finished recordings yet.",
    byShowFailed: "Could not load space by show.",
    nfo: "Write .nfo files for Plex, Jellyfin, and Kodi",
    nfoHint: "A file beside each finished recording, with the title and description.",
    reserve: "Keep this much free",
    reserveHint: "Use 0 to turn the reserve off. A show already recording is left alone.",
    buffer: "Keep for recording from the start",
    bufferHint: "While a channel is on, the server keeps up to this much of it, so recording a show already on starts from its beginning. It uses at most half the free space.",
    backup: "Download backup",
    backups: "Backups",
    backupHint: "The backup is the catalog. Recordings stay put. Seven nightly copies and four weekly copies are kept. A copy is saved before an update.",
    backupEmpty: "No backups yet.",
    backupFailed: "Could not load backups.",
    backupDownload: "Download",
    backupNightly: "Nightly",
    backupWeekly: "Weekly",
    backupUpdate: "Update",
    restore: "Restore",
    restoreConfirm: "Restore this backup? The catalog goes back to that copy. Recordings stay.",
    restoreFailed: "Could not restore that backup.",
    support: "Download a support bundle",
    supportHint: "Logs, versions, and settings. Passwords are left out.",
    guideAccount: "Schedules Direct",
    guideAccountHint: "Fills channels the tuner guide skips. Fourteen days when the account allows it.",
    guideLineup: "Lineup",
    guideAddress: "Guide address",
    guideAddressHint: "An XMLTV link for channels the tuner guide skips.",
    movieArt: "Movie artwork",
    movieArtHint: "Fills posters the guide does not include.",
    hideScores: "Hide scores",
    hideScoresHint: "A recorded game stays hidden until you watch it.",
    scoresFrom: "Scores from ESPN's public scoreboard",
    scoresFromSportsDB: "Scores from TheSportsDB",
    liveScores: "Live scores",
    liveScoresHint: "On asks your server for the scoreboard. Off sends nothing.",
    sportsdbKey: "TheSportsDB key",
    sportsdbKeyHint: "Optional. Your own key. None is included.",
    updates: "Check for updates",
    updatesHint: "Once a day. Nothing else is sent.",
    passwordTitle: "This server is for the home network",
    passwordBody: "A password is required before remote access.",
    profile: "Profile",
  },
  player: {
    encrypted: "The 3.0 version is encrypted. Showing the regular broadcast.",
    stats: "Stats",
    delayApple: "An Apple device is watching, so this channel stays at Balanced.",
    playing: "Playing",
    source: "Source",
    output: "Output",
    tuner: "Tuner",
    bitrate: "Bitrate",
    dropped: "Dropped frames",
    buffer: "Buffer ahead",
    behind: "Behind live",
    drift: "Sync drift",
    rendition: "Rendition",
    encoder: "Encoder",
    sound: "Sound",
    waiting: "Waiting",
    helpTitle: "Keyboard",
    close: "Close",
    sleep: "Sleep",
    sleep30: "Stops in 30 minutes.",
    sleep60: "Stops in 1 hour.",
    sleep90: "Stops in 90 minutes.",
    sleepHint: "Sleep, in Options, stops the picture after 30, 60, or 90 minutes.",
    volume: "Volume",
    keys: [
      ["Space", "Play or pause"],
      ["Left", "Back 15 seconds"],
      ["Right", "Ahead 30 seconds"],
      ["Up", "Previous channel"],
      ["Down", "Next channel"],
      ["Escape or Backspace", "Back to browsing"],
      ["L", "Last channel"],
      ["G", "Channels"],
      ["I", "Stats"],
      ["M", "Side by side"],
      ["R", "Record"],
      ["C", "Captions"],
      ["T", "Theater"],
      ["?", "This list"],
      ["0–9", "Channel number"],
    ],
  },
} as const;
